export type CurrencySymbolPosition = 'before' | 'after';

export type MinorUnitDigits = 0 | 2;
export type MinorUnitFactor = 1 | 100;

export type CurrencyCatalogEntry = {
  code: string;
  name: string;
  pluralName: string;
  /** Símbolo tal como lo usa el país de origen de la moneda, no un código
   * inventado para desambiguar: por ejemplo, el peso colombiano usa «$», no
   * «CO$», igual que el dólar estadounidense o el mexicano. */
  symbol: string;
  /** Lado del importe donde ese país coloca el símbolo. */
  symbolPosition: CurrencySymbolPosition;
  /** Emoji de la bandera del país o unión representativa de la moneda. */
  flag: string;
  /** Países donde se usa la moneda, para poder buscarla por país. */
  countries: readonly string[];
  /** Número de decimales oficiales de la unidad menor. */
  minorUnitDigits: MinorUnitDigits;
};

/**
 * Catálogo curado de monedas admitidas. Cubre las divisas más usadas a nivel
 * global y las de los países hispanohablantes, evitando mantener el listado
 * completo ISO 4217 que la aplicación todavía no necesita.
 *
 * Los símbolos y su posición reproducen el uso real de cada país (por
 * ejemplo, «Bs.» para el bolívar venezolano y el boliviano, o «$» a la
 * izquierda del importe para el peso colombiano, mexicano, argentino,
 * chileno, uruguayo, canadiense, australiano y neozelandés), en vez de
 * variantes desambiguadas como «CO$» o «MX$» que esos países no usan. El
 * código ISO junto al nombre y la bandera siguen distinguiendo cada moneda
 * cuando dos comparten símbolo.
 */
export const currencyCatalog = [
  {
    code: 'EUR',
    name: 'Euro',
    pluralName: 'euros',
    symbol: '€',
    symbolPosition: 'after',
    flag: '🇪🇺',
    countries: [
      'Unión Europea',
      'España',
      'Alemania',
      'Francia',
      'Italia',
      'Portugal',
    ],
    minorUnitDigits: 2,
  },
  {
    code: 'USD',
    name: 'Dólar estadounidense',
    pluralName: 'dólares estadounidenses',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇺🇸',
    countries: ['Estados Unidos'],
    minorUnitDigits: 2,
  },
  {
    code: 'GBP',
    name: 'Libra esterlina',
    pluralName: 'libras esterlinas',
    symbol: '£',
    symbolPosition: 'before',
    flag: '🇬🇧',
    countries: ['Reino Unido'],
    minorUnitDigits: 2,
  },
  {
    code: 'JPY',
    name: 'Yen japonés',
    pluralName: 'yenes',
    symbol: '¥',
    symbolPosition: 'before',
    flag: '🇯🇵',
    countries: ['Japón'],
    minorUnitDigits: 0,
  },
  {
    code: 'CHF',
    name: 'Franco suizo',
    pluralName: 'francos suizos',
    symbol: 'CHF',
    symbolPosition: 'before',
    flag: '🇨🇭',
    countries: ['Suiza'],
    minorUnitDigits: 2,
  },
  {
    code: 'CAD',
    name: 'Dólar canadiense',
    pluralName: 'dólares canadienses',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇨🇦',
    countries: ['Canadá'],
    minorUnitDigits: 2,
  },
  {
    code: 'AUD',
    name: 'Dólar australiano',
    pluralName: 'dólares australianos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇦🇺',
    countries: ['Australia'],
    minorUnitDigits: 2,
  },
  {
    code: 'MXN',
    name: 'Peso mexicano',
    pluralName: 'pesos mexicanos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇲🇽',
    countries: ['México'],
    minorUnitDigits: 2,
  },
  {
    code: 'ARS',
    name: 'Peso argentino',
    pluralName: 'pesos argentinos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇦🇷',
    countries: ['Argentina'],
    minorUnitDigits: 2,
  },
  {
    code: 'CLP',
    name: 'Peso chileno',
    pluralName: 'pesos chilenos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇨🇱',
    countries: ['Chile'],
    minorUnitDigits: 0,
  },
  {
    code: 'COP',
    name: 'Peso colombiano',
    pluralName: 'pesos colombianos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇨🇴',
    countries: ['Colombia'],
    minorUnitDigits: 2,
  },
  {
    code: 'PEN',
    name: 'Sol peruano',
    pluralName: 'soles peruanos',
    symbol: 'S/',
    symbolPosition: 'before',
    flag: '🇵🇪',
    countries: ['Perú'],
    minorUnitDigits: 2,
  },
  {
    code: 'UYU',
    name: 'Peso uruguayo',
    pluralName: 'pesos uruguayos',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇺🇾',
    countries: ['Uruguay'],
    minorUnitDigits: 2,
  },
  {
    code: 'BRL',
    name: 'Real brasileño',
    pluralName: 'reales brasileños',
    symbol: 'R$',
    symbolPosition: 'before',
    flag: '🇧🇷',
    countries: ['Brasil'],
    minorUnitDigits: 2,
  },
  {
    code: 'BOB',
    name: 'Boliviano',
    pluralName: 'bolivianos',
    symbol: 'Bs.',
    symbolPosition: 'before',
    flag: '🇧🇴',
    countries: ['Bolivia'],
    minorUnitDigits: 2,
  },
  {
    code: 'PYG',
    name: 'Guaraní paraguayo',
    pluralName: 'guaraníes paraguayos',
    symbol: 'Gs.',
    symbolPosition: 'before',
    flag: '🇵🇾',
    countries: ['Paraguay'],
    minorUnitDigits: 0,
  },
  {
    code: 'VES',
    name: 'Bolívar venezolano',
    pluralName: 'bolívares venezolanos',
    symbol: 'Bs.',
    symbolPosition: 'before',
    flag: '🇻🇪',
    countries: ['Venezuela'],
    minorUnitDigits: 2,
  },
  {
    code: 'CRC',
    name: 'Colón costarricense',
    pluralName: 'colones costarricenses',
    symbol: '₡',
    symbolPosition: 'before',
    flag: '🇨🇷',
    countries: ['Costa Rica'],
    minorUnitDigits: 2,
  },
  {
    code: 'GTQ',
    name: 'Quetzal guatemalteco',
    pluralName: 'quetzales guatemaltecos',
    symbol: 'Q',
    symbolPosition: 'before',
    flag: '🇬🇹',
    countries: ['Guatemala'],
    minorUnitDigits: 2,
  },
  {
    code: 'HNL',
    name: 'Lempira hondureño',
    pluralName: 'lempiras hondureños',
    symbol: 'L',
    symbolPosition: 'before',
    flag: '🇭🇳',
    countries: ['Honduras'],
    minorUnitDigits: 2,
  },
  {
    code: 'NIO',
    name: 'Córdoba nicaragüense',
    pluralName: 'córdobas nicaragüenses',
    symbol: 'C$',
    symbolPosition: 'before',
    flag: '🇳🇮',
    countries: ['Nicaragua'],
    minorUnitDigits: 2,
  },
  {
    code: 'PAB',
    name: 'Balboa panameño',
    pluralName: 'balboas panameños',
    symbol: 'B/.',
    symbolPosition: 'before',
    flag: '🇵🇦',
    countries: ['Panamá'],
    minorUnitDigits: 2,
  },
  {
    code: 'DOP',
    name: 'Peso dominicano',
    pluralName: 'pesos dominicanos',
    symbol: 'RD$',
    symbolPosition: 'before',
    flag: '🇩🇴',
    countries: ['República Dominicana'],
    minorUnitDigits: 2,
  },
  {
    code: 'CNY',
    name: 'Yuan chino',
    pluralName: 'yuanes chinos',
    symbol: '¥',
    symbolPosition: 'before',
    flag: '🇨🇳',
    countries: ['China'],
    minorUnitDigits: 2,
  },
  {
    code: 'INR',
    name: 'Rupia india',
    pluralName: 'rupias indias',
    symbol: '₹',
    symbolPosition: 'before',
    flag: '🇮🇳',
    countries: ['India'],
    minorUnitDigits: 2,
  },
  {
    code: 'SEK',
    name: 'Corona sueca',
    pluralName: 'coronas suecas',
    symbol: 'kr',
    symbolPosition: 'after',
    flag: '🇸🇪',
    countries: ['Suecia'],
    minorUnitDigits: 2,
  },
  {
    code: 'NOK',
    name: 'Corona noruega',
    pluralName: 'coronas noruegas',
    symbol: 'kr',
    symbolPosition: 'after',
    flag: '🇳🇴',
    countries: ['Noruega'],
    minorUnitDigits: 2,
  },
  {
    code: 'DKK',
    name: 'Corona danesa',
    pluralName: 'coronas danesas',
    symbol: 'kr.',
    symbolPosition: 'after',
    flag: '🇩🇰',
    countries: ['Dinamarca'],
    minorUnitDigits: 2,
  },
  {
    code: 'PLN',
    name: 'Zloty polaco',
    pluralName: 'zlotys polacos',
    symbol: 'zł',
    symbolPosition: 'after',
    flag: '🇵🇱',
    countries: ['Polonia'],
    minorUnitDigits: 2,
  },
  {
    code: 'TRY',
    name: 'Lira turca',
    pluralName: 'liras turcas',
    symbol: '₺',
    symbolPosition: 'before',
    flag: '🇹🇷',
    countries: ['Turquía'],
    minorUnitDigits: 2,
  },
  {
    code: 'NZD',
    name: 'Dólar neozelandés',
    pluralName: 'dólares neozelandeses',
    symbol: '$',
    symbolPosition: 'before',
    flag: '🇳🇿',
    countries: ['Nueva Zelanda'],
    minorUnitDigits: 2,
  },
] as const satisfies readonly CurrencyCatalogEntry[];
