export const motion = {
  categoryPageIndicatorSpring: {
    dampingRatio: 0.62,
    duration: 680,
  },
  calendarResetFadeInDuration: 300,
  calendarResetFadeOutDuration: 200,
  calendarViewTransitionDuration: 180,
  calendarContentMaxDelay: 120,
  calendarContentStagger: 12,
  chartContentEnterDelay: 300,
  chartContentExitDuration: 300,
  chartContentFadeDuration: 180,
  chartContentStagger: 64,
  chartContentTravel: 56,
  chartModeSpring: {
    damping: 16,
    mass: 0.68,
    stiffness: 155,
  },
  chartRevealDuration: 620,
  chartRevealStagger: 55,
  disclosureExitDuration: 160,
  disclosureItemStagger: 56,
  disclosureRevealDuration: 240,
  floatingButtonVisibilityDuration: 280,
  inputPulseDuration: 48,
  onboardingTextRevealBlockDuration: 420,
  onboardingTextRevealBlockTravel: 10,
  onboardingTextRevealBlockPause: 120,
  authSuccessAutoContinueDelay: 1600,
  stepProgressFillDuration: 540,
  stickyHeaderTransitionDuration: 240,
  stickySummaryPulseDuration: 90,
  tabIconSelectSpring: {
    damping: 14,
    mass: 0.4,
    stiffness: 260,
  },
  transactionTypeSpring: {
    damping: 14,
    mass: 0.55,
    stiffness: 260,
  },
  toastTransitionDuration: 260,
  toastVisibleDuration: 3200,
  disclosureSpring: {
    damping: 18,
    mass: 0.72,
    stiffness: 170,
  },
} as const;
