export const motion = {
  loadingBarDuration: 700,
  loadingBarCrawlDuration: 4000,
  loadingCompletionDuration: 160,
  loadingTransitionDuration: 260,
  startupRevealDuration: 480,
  startupRevealStagger: 36,
  startupRevealMaxDelay: 216,
  startupRevealTravel: 16,
  categoryPageIndicatorSpring: {
    dampingRatio: 0.62,
    duration: 680,
  },
  calendarResetFadeInDuration: 300,
  calendarResetFadeOutDuration: 200,
  calendarViewTransitionDuration: 180,
  categoryAmountTransitionDuration: 350,
  categoryAmountSwitchInterval: 8000,
  calendarContentMaxDelay: 120,
  calendarContentStagger: 12,
  categoryViewTransitionDuration: 180,
  categoryViewTransitionTravel: 28,
  chartContentEnterDelay: 300,
  chartContentExitDuration: 300,
  chartContentFadeDuration: 180,
  chartContentStagger: 64,
  chartContentTravel: 56,
  chartModeSpring: {
    damping: 16,
    mass: 0.68,
    stiffness: 155,
  },
  chartRevealDuration: 620,
  chartRevealStagger: 55,
  disclosureExitDuration: 160,
  disclosureItemStagger: 56,
  disclosureRevealDuration: 240,
  floatingButtonVisibilityDuration: 280,
  inputPulseDuration: 48,
  onboardingTextRevealBlockDuration: 420,
  onboardingTextRevealBlockTravel: 10,
  onboardingTextRevealBlockPause: 120,
  authSuccessAutoContinueDelay: 1600,
  stepProgressFillDuration: 540,
  stickyHeaderTransitionDuration: 240,
  stickySummaryPulseDuration: 90,
  tabIconSelectSpring: {
    damping: 14,
    mass: 0.4,
    stiffness: 260,
  },
  transactionTypeSpring: {
    damping: 14,
    mass: 0.55,
    stiffness: 260,
  },
  toastTransitionDuration: 260,
  toastVisibleDuration: 3200,
  /** Un aviso con acción espera a que la persona pueda leerlo y pulsar. */
  toastActionVisibleDuration: 8000,
  disclosureSpring: {
    damping: 18,
    mass: 0.72,
    stiffness: 170,
  },
} as const;
